paritytech/scripts

optimize.sh
file to optimizations settings for nodes on ubuntu based systems
=> optimize.sh

install-parity.sh
=> Update install-parity.sh Ubuntu deb for 1.5.7

install-parity.sh
Should fix #8 
Needs testing on Ubuntu and MacOS.
=> Check the version string of installed binary, ref #8

docker-files-for-Gitlab-CI-rust/docker-build.sh, docker-files-for-Gitlab-CI-rust/libp2p-js-echo-server/Dockerfile, docker-files-for-Gitlab-CI-rust/libp2p-js-echo-server/Makefile, docker-files-for-Gitlab-CI-rust/libp2p-js-echo-server/README.md
Desirable for adding a test that checks whether our Rust port of libp2p can successfully connect to it.
The working directory handling is a bit of a clusterfuck. Let me know if I need to fix it.
cc https://github.com/libp2p/rust-libp2p/pull/112
=> Add an image of the JS libp2p echo listener

get-parity.sh
Script has become noisy. I propose adding -sS to the curl commands
-S, --show-error    Show error. With -s, make curl show errors when they occur
-s, --silent        Silent mode (don't output anything)
=> Silence Curl

get-parity.sh
fixes https://github.com/paritytech/scripts/issues/20
after https://github.com/paritytech/parity/pull/7870
cc @fevo1971
=> stable should install stable-release

get-parity.sh
Tested just this script locally by specifying version and default version
fix #32
=> Fixed extra pipe causing installs to fail

get-substrate.sh
Closes: https://github.com/paritytech/substrate/issues/1240
=> Adds missing dependencies and does some cleanup

get-parity.sh
=> Revert "Update to 2.2.5-beta and 2.1.10-stable"

docker-files-for-Gitlab-CI-rust/parity-eth-linux-ci/Dockerfile, docker-files-for-Gitlab-CI-rust/parity-eth-linux-ci/Makefile, docker-files-for-Gitlab-CI-rust/parity-eth-linux-ci/README.md, docker-files-for-Gitlab-CI-rust/rustup/Dockerfile, docker-files-for-Gitlab-CI-rust/rustup/Makefile
- shrinked, 
- no useless pkges,
- pre-clone repos,
- new cache handler,
- less steps,
- ready for using cache in docker volumes
=> New Dockerfile

docker-files-for-Gitlab-CI-rust/cross/android/Dockerfile
- smaller
- optimized
- with cache
=> Android dockerfile update

docker-files-for-Gitlab-CI-rust/substrate-linux-ci/Dockerfile
- cleaned unused dependencies
Tests and build run successfully.
Please tell if I've deleted something important.
=> speed and weight improvements

.gitlab-ci.yml, kubetools/Dockerfile
fixed 
removed wget 
applied standards for kube image
=> fix kubetools image

get-substrate.sh
From `pacman -Sh:`
```
-u, --sysupgrade     upgrade installed packages (-uu enables downgrades) # this may actually not be necessary and could be done independently.
-y, --refresh        download fresh package databases from the server
--needed         do not reinstall up to date packages
```
=> Adjust Arch Linux installation of dependencies

dockerfiles/parity-ci-arm64/Dockerfile, dockerfiles/parity-ci-armhf/Dockerfile, dockerfiles/parity-ci-i386/Dockerfile
Fixed where I forgot to mention the repository.
=> forgot registry name

dockerfiles/awscli/Dockerfile, dockerfiles/deploy/Dockerfile, dockerfiles/kubetools/Dockerfile, dockerfiles/parity-ci-android/Dockerfile, dockerfiles/parity-ci-arm64/Dockerfile, dockerfiles/parity-ci-armhf/Dockerfile, dockerfiles/parity-ci-docs/Dockerfile, dockerfiles/parity-ci-i386/Dockerfile, dockerfiles/rust-coverage/Dockerfile, dockerfiles/tools/Dockerfile
=> Fix for variables and metadata

dockerfiles/parity-ci-android/README.md, dockerfiles/parity-ci-arm64/Dockerfile, dockerfiles/parity-ci-arm64/README.md, dockerfiles/parity-ci-arm64/config, dockerfiles/parity-ci-armhf/Dockerfile, dockerfiles/parity-ci-armhf/README.md, dockerfiles/parity-ci-armhf/config, dockerfiles/parity-ci-i386/README.md
- Fix xcompilation for armv7
- Fix xcompilation for armv8
- update docs
=> Fix xcompilation for armv7, armv8, update docs

get-substrate.sh
- Added exit instruction to stop invalid execution.
- Build subkey using nightly.
=> Fix subkey installation

get-substrate.sh
- Improve installation time by compiling on the same temp directory.
=> Install Substrate and subkey from same repo

install-wasm-binaries.sh
- Migrate the script from the substrate-developer-hub/substrate-contracts-workshop repo.
=> Add Debian wasm-binaries script

get-substrate.sh
- Upgrades brew to prevent install error.
- Adds nightly deps for rust.
=> Fix brew upgrade dependecies

.gitlab-ci.yml, dockerfiles/ink-ci-linux/Dockerfile, dockerfiles/ink-ci-linux/README.md
Adds new image for `ink` project CI. 
More in README.md
=> new image for ink CI

.gitlab-ci.yml, dockerfiles/ink-ci-linux/Dockerfile, dockerfiles/ink-ci-linux/README.md
installed `kcov` to measure coverage.
=> Ink builder

dockerfiles/ink-ci-linux/README.md
- made lists vertical for improved readability
- ordered lists
- removed some wrong infos
- update to `nightly-2019-10-03`
=> update ink! README

dockerfiles/ink-ci-linux/Dockerfile, dockerfiles/ink-ci-linux/README.md
- `grcov` for code coverage
- new rustlang version
=> grcov and new rust

dockerfiles/ink-ci-linux/Dockerfile, dockerfiles/ink-ci-linux/README.md
now `cargo-contract` is installed in CI
=> Remove contract from ink

dockerfiles/ink-ci-linux/Dockerfile, dockerfiles/ink-ci-linux/README.md
Returns `cargo-contract` to `ink!` dockerfile
=> add contract to ink

.gitlab-ci.yml, dockerfiles/redis_exporter/Dockerfile, dockerfiles/redis_exporter/README.md
deployment suggestion: https://mehmandarov.com/start-docker-containers-automatically/ running it inside docker with systemd.
=> docker container build with redis_exporter

.gitlab-ci.yml
introduce a built-in container scanner
=> container scanner

.gitlab-ci.yml
Reverts paritytech/scripts#130
=> Revert "container scanner"

dockerfiles/contracts-ci-linux/Dockerfile
needed for `cargo-contracts` CI.
=> fmt for contracts

get-parity.sh
Currently a bug in v2.7.0 causing crashes. Pulling the release until further investigation is complete
=> Revert v2.7.0 and beta

dockerfiles/ink-ci-linux/Dockerfile
update nightly to 2020-02-17 for ink image
=> update nightly for ink image

wasm-utils/install-rust-lld-ARM.sh, wasm-utils/install-wasm-binaries.sh
Improves ARM-rust-lld clone speed.
Updates wasm-binaries requirement for ink! contracts.
=> Update Wasm Scripts

get-parity.sh, get-substrate.sh
Just linted these scrips and fixed one typo.
=> lint for get scripts

dockerfiles/bridge-ci-linux/Dockerfile
https://github.com/paritytech/devops/issues/413
=> solc stable version

.gitlab-ci.yml, dockerfiles/chaostools/Dockerfile, dockerfiles/chaostools/README.md
=> add chaostools

dockerfiles/ink-ci-linux/Dockerfile
=> Add rust-covfix for code coverage

.gitlab-ci.yml
- fixes docker scanner remediation for internal images
- simplifies variables
=> Fix scanner remediation

.gitlab-ci.yml
Reverts paritytech/scripts#192 needs testing
=> Revert "Prep to deprecation in GitLab 13"

.gitlab-ci.yml
Adds to changes from the reverted https://github.com/paritytech/scripts/pull/192
- removed `{}` for readability
- merged `$DOCKERIMAGE` to `$IMAGE_NAME`
- tried a bunch of different approaches, couldn't make `rules:` to work how I want, reverted to `only:`, this is supposed to work on v13
- removed `environment:` and some other unnecessary clauses mentioned in https://github.com/paritytech/scripts/pull/192
=> Prep for GitLab v13

dockerfiles/contracts-ci-linux/Dockerfile
using `solang` image to get the binary from
=> contracts ci image change how solang is installed

dockerfiles/contracts-ci-linux/Dockerfile
This is needed for https://github.com/paritytech/pallet-contracts-waterfall/pull/84
=> Move to solang m7

retag.sh
Handy to promptly retag the image.
=> Script to retag the docker image without uploading it

get-substrate.sh
I do not have a Mac so I am not able to test this.
Ref: https://brew.sh/
=> Update command to install Homebrew

.gitlab-ci.yml
Substrate companion: https://github.com/paritytech/substrate/pull/6606
=> new stable test

.gitlab-ci.yml, dockerfiles/chaostools/Dockerfile
update parity/chaostools image version:
node:
<del>12-alphine</del> 14-alphine 
kubectl:
<del>1.14.6</del> 1.18.2
=> bump node version to v14 to get rid of node-gyp issue

dockerfiles/terraform/Dockerfile
=> update tf to v0.13.4

.gitlab-ci.yml
follow-up of https://github.com/paritytech/scripts/pull/226
=> bump terraform to v0.13.4

dockerfiles/contracts-ci-linux/Dockerfile
for https://github.com/paritytech/cargo-contract/pull/86
=> temporary override for contracts' CI nightly toolchain

wasm-utils/install-wasm-binaries.sh
=> Fix wasm-opt untar

dockerfiles/sccache-ci-linux/Dockerfile
=> WIP: new image for sccache CI

dockerfiles/ci-linux/Dockerfile
- bumps the version of `diener`
=> dockerfile: bump diener

.gitlab-ci.yml
Updates the tests for the CI image according to substrate CI.
=> CI: update substrate tests

.gitlab-ci.yml
Some best practices according to https://github.com/aquasecurity/trivy#gitlab-ci-using-trivy-container
=> CI: optimize trivy scanner job

dockerfiles/ci-linux/Dockerfile
- fix cargo-deny installation
- fail on errors
=> dockerfiles: fix cargo-deny installation; fail on errors

dockerfiles/ink-ci-linux/Dockerfile, dockerfiles/ink-ci-linux/README.md
=> dockerfiles: update cargo-contract in ink CI image

dockerfiles/contracts-ci-linux/Dockerfile, dockerfiles/ink-ci-linux/Dockerfile
Closes https://github.com/paritytech/ci_cd/issues/108.
=> Install `binaryen` dependency for `cargo-contract`

dockerfiles/ink-ci-linux/Dockerfile, dockerfiles/ink-ci-linux/README.md
Needed for https://github.com/paritytech/ink/pull/718.
=> Add packages which enable automated spell-checking

dockerfiles/ci-linux/Dockerfile
As required in https://github.com/paritytech/substrate/pull/8625
=> dockerfile: wasm-bindgen-cli update

.gitlab-ci.yml
after their CI is real, it will be changed to have a test and a production tag
=> CI: produce a one stage img for bridges CI

dockerfiles/ansible/Dockerfile
I tested the changes by building an image on my machine and running [the `deploy.yml` playbook in `staking-ops-tools`](https://github.com/paritytech/staking-ops-tools/tree/hs-purge-elastic/.maintain/ansible) with it.
=> Update ansible image

dockerfiles/base-ci-linux/Dockerfile, dockerfiles/base-ci/Dockerfile, dockerfiles/bridges-ci/Dockerfile, dockerfiles/ci-linux/Dockerfile, dockerfiles/contracts-ci-linux/Dockerfile, dockerfiles/ink-ci-linux/Dockerfile, dockerfiles/ink-waterfall-ci/Dockerfile, dockerfiles/sccache-ci-ubuntu/Dockerfile
Relates to paritytech/ci_cd#92.
=> Non-root user for most of the CI images

dockerfiles/ink-ci-linux/Dockerfile
I need this to run some commands in parallel, within CI jobs.
=> Install `parallel` for ink! related containers

.gitlab-ci.yml, dockerfiles/cachepot-ci/Dockerfile, dockerfiles/cachepot-ci/README.md
rename registry and image name, keep old `sccache` as it's still installed here.
=> dockerfile: rename to cachepot

gitlab/README.md, gitlab/wipe-inactive-runners
```
Usage: wipe-inactive-runners [options]
--tag RUNNER TAG             Which runner's tag to clean up
--dry-run                    Just output what will be removed
```
=> Add `wipe-inactive-runners` script

dockerfiles/kubetools/helm3.Dockerfile
=> Fix helm diff plugin installation

.gitlab-ci.yml
Complements https://github.com/paritytech/scripts/pull/333.
`buildah logout` is affected too.
_cc https://github.com/paritytech/ci_cd/issues/190_
=> Use `$REGISTRY_NAME` for `buildah logout` too

snippets/.bashrc
=> Format podman command in .bashrc

dockerfiles/ci-linux/Dockerfile
Added clippy to ci-linux Dockerfile.
Related to https://github.com/paritytech/cumulus/pull/616
=> Add clippy to ci-linux

dockerfiles/cachepot-ci/Dockerfile
=> cachepot-ci: Add missing dependencies for broot

dockerfiles/base-ci-linux/Dockerfile, dockerfiles/base-ci/Dockerfile
Closes https://github.com/paritytech/ci_cd/issues/285
cc @joao-paulo-parity
=> Add python3 and pip to base-ci-linux

dockerfiles/multisig-ci/Dockerfile
Added kubectl to multisig docker image for this PR: https://github.com/paritytech/multisig-commander/pull/147
=> add kubectl to multisig image

.gitlab-ci.yml
Added downstream project (polkadot) for ci-linux
Closes https://github.com/paritytech/ci_cd/issues/249
Should be merged after https://github.com/paritytech/polkadot/pull/4663
=> Add polkadot downstream

dockerfiles/kubetools/helm3.Dockerfile
Adding the yq package to easily merge yaml files
=> Include yq package

dockerfiles/contracts-ci-linux/Dockerfile
This reverts commit edadab47f102e431313ba1caf2cb97b49926203c.
=> Revert "Revert me: Set fixed Rust nighly version"

dockerfiles/base-ci-linux/Dockerfile, dockerfiles/base-ci-linux/README.md, dockerfiles/utility/base-ci-linux-config
Resolves https://github.com/paritytech/ci_cd/issues/324.
=> Use `clang-13` for `paritytech/base-ci-linux`

dockerfiles/base-ci-linux/Dockerfile
=> Add `gnupg` for `apt-key`

dockerfiles/benchmarks/Dockerfile, dockerfiles/benchmarks/README.md, dockerfiles/benchmarks/check_single_bench_result.py
Added script that checks single result and creates github issue.
Part of https://github.com/paritytech/ci_cd/issues/174
=> Add check_single_bench_result.py

dockerfiles/parity-scale-codec/Dockerfile, dockerfiles/parity-scale-codec/README.md
Fixes from this pr: https://github.com/paritytech/scripts/pull/392
=> [scale-codec-ci] small fixes

dockerfiles/kubetools/helm3.Dockerfile
The PR adds `vals` and `helm-secret` plugins and `vault` binary to `helm3` CI image.
=> add helm-secrets and vals plugins to helm3 ci image

.gitlab-ci.yml
PR changes CI variables to use group variables as they are the same.
=> Change vars to use group one's

.gitlab-ci.yml, dockerfiles/deb/Dockerfile, dockerfiles/deb/README.md, dockerfiles/gnupg/Dockerfile, dockerfiles/gnupg/README.md, dockerfiles/rpm/Dockerfile, dockerfiles/rpm/README.md
resolves https://github.com/paritytech/ci_cd/issues/414
resolves https://github.com/paritytech/ci_cd/issues/415
see also https://github.com/paritytech/cleanroom/pull/26
=> Add RelEng packaging containers

dockerfiles/rpm/Dockerfile, dockerfiles/rpm/rpmmacros
see https://github.com/paritytech/cleanroom/pull/26#issuecomment-1118519963
=> rpm: add .rpmmacros to image

dockerfiles/ci-linux/Dockerfile
Resolves paritytech/ci_cd#427.
=> Bump Rust nightly to `2022-05-12`

dockerfiles/deb/Dockerfile, dockerfiles/gnupg/Dockerfile, dockerfiles/rpm/Dockerfile
Closes: https://github.com/paritytech/ci_cd/issues/428
=> dockerfiles: fix args placement

.gitlab-ci.yml, dockerfiles/lz4/Dockerfile, dockerfiles/lz4/README.md
Add new Dockerfile with lz4 and wget. Will be used in https://github.com/paritytech/helm-charts/pull/80
=> Add new Dockerfile with lz4 and wget

dockerfiles/ws-health-exporter/Dockerfile, dockerfiles/ws-health-exporter/README.md, dockerfiles/ws-health-exporter/exporter.py
Add a health checker for Substrate-based nodes. This is a temporary solution which should be eventually replaced by https://github.com/paritytech/substrate/issues/1017
=> Add Dockerfile for ws-health-exporter

dockerfiles/cachepot-ci/Dockerfile
Fix the GPG error for the NVIDIA repo, otherwise the image won't be built.
=> Fix NVIDIA repository verification

.gitlab-ci.yml
I added the image a while back but did not add CI back then
=> Add CI task for the parity-keyring image

.gitlab-ci.yml
Update tools version for `helm:3` and `sops` image.
=> Update tools versions

.gitlab-ci.yml, dockerfiles/kubetools/kubectl-1.22.Dockerfile
=> Kubectl Image

.gitlab-ci.yml
Small fixes in the CI for Kubetools
=> Update kubetools CI

.gitlab-ci.yml
Removal of comment which invalidates Gitlab CI
=> Update Gitlab CI file

.gitlab-ci.yml
To build new terraform docker image
=> update terraform version

dockerfiles/ink-waterfall-ci/Dockerfile
:t-rex: 
https://gitlab.parity.io/parity/mirrors/scripts/-/jobs/1936725#L3119
=> Fix ink waterfall CI

dockerfiles/mitogen/Dockerfile
=> Update mitogen docker images

dockerfiles/ci-linux/Dockerfile
cc https://github.com/paritytech/ci_cd/issues/670
=> [ci-linux] Upgrade diener

.gitlab-ci.yml
current version is broken, reverting the previous one
=> fix buildah image

dockerfiles/ci-linux/Dockerfile
changing git ref to an older one (the latest one breaks cbs)
=> [ci-linux] diener 0.4.4

.gitlab-ci.yml, dockerfiles/ansible/Dockerfile, dockerfiles/ci-linux/Dockerfile
Currently we don't check that image can be built when we change something in dockerfiles. PR fixes this (currently in progress).
=> [ci] add build docker stage in PRs

dockerfiles/ci-linux/Dockerfile
Updated nightly needed for https://github.com/paritytech/ci_cd/issues/678
=> [ci-linux] Update rust nightly to 2022-11-13

.gitlab-ci.yml, dockerfiles/mdbook-utils/Dockerfile, dockerfiles/mdbook-utils/README.md
cc https://github.com/paritytech/ci_cd/issues/679
=> Add mdbook-utils image

dockerfiles/ws-health-exporter/exporter.py
=> Make WSS exporter port configurable

dockerfiles/base-ci-linux/Dockerfile, dockerfiles/base-ci/Dockerfile
Needed for https://github.com/paritytech/ci_cd/issues/698.
=> Add Zstandard to the base CI images

dockerfiles/ci-linux/Dockerfile
Fixes https://github.com/nextest-rs/nextest/issues/732.
=> Install `nextest` with `--locked`

dockerfiles/ci-linux/Dockerfile
Needed for https://github.com/paritytech/ci_cd/issues/704
=> [ci] Install latest git in ci-linux

.gitlab-ci.yml
cc https://github.com/paritytech/ci_cd/issues/738
=> Add CI for xbuilder-aarch64-unknown-linux-gnu

dockerfiles/xbuilder-aarch64-unknown-linux-gnu/Dockerfile
cc https://github.com/paritytech/ci_cd/issues/738
=> Fix FROM in xbuilder

dockerfiles/releng-scripts/Dockerfile
This PR adds the missing tooling to the releng-scripts docker image.
=> Add missing tooling

dockerfiles/base-ci-linux/Dockerfile, dockerfiles/base-ci-linux/README.md, dockerfiles/ci-linux/Dockerfile, dockerfiles/ci-linux/README.md, dockerfiles/parity-scale-codec/Dockerfile, dockerfiles/parity-scale-codec/README.md
first step of https://github.com/paritytech/ci_cd/issues/766
=> base-ci-linux: use debian bullseye base image

dockerfiles/tools/Dockerfile
I need some lightweight image manipulation tool in one of the our images, so I decided to settle on `skopeo` here.
=> Add `skopeo` to the `tools` image

dockerfiles/ws-health-exporter/Dockerfile, dockerfiles/ws-health-exporter/README.md, dockerfiles/ws-health-exporter/exporter.py
* added new environment variables to setup existing and new preferences.
* added the list of WebSocket URLs feature and the `url` metric tag.
* added the block drift check. it is disabled by default.
* logging preferences were refactored. It allows to use common logger for all modules.
* added the production HTTP server
* README.md was added
=> ws-health-exporter was improved

dockerfiles/ws-health-exporter/exporter.py
it fixes backward compatibility
=> fix ws-health-exporter

.gitlab-ci.yml
resolves paritytech/ci_cd/issues/776
=> feat(ci-linux): tag staging images with rust & debian version

dockerfiles/base-ci-linux/Dockerfile
Workarounds https://github.com/minio/mc/issues/4547.
=> Pin MinIO client version

dockerfiles/base-ci-linux/Dockerfile
It's needed for xml to json transformation.
=> Install xy in `base-ci-linux` image

.gitlab-ci.yml
=> Fix indentation

dockerfiles/releng-scripts/Dockerfile
companion to https://github.com/paritytech/releng-scripts/pull/41
=> rename `rs` to `releng-scripts`

.gitlab-ci.yml
Follow-up to https://github.com/paritytech/scripts/pull/575
=> Update gitlab-ci for kubetools-kubectl

.gitlab-ci.yml
need for 
DATESTAMP=$(git log -1 --pretty=format:"%ad" --date=format:"%Y%m%d" -- dockerfiles/$IMAGE_NAME/Dockerfile)
=> install git in ci-unified job

dockerfiles/ci-unified/Dockerfile
Needed to fix https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3221658
=> [ci-unified] add rust-analyzer to nightly

.gitlab-ci.yml, dockerfiles/kube-manifests-validation/Dockerfile, dockerfiles/kube-manifests-validation/README.md, dockerfiles/kube-manifests-validation/datree-config.yaml, dockerfiles/kube-manifests-validation/datree-policies.yaml
Add base image with the tools for validating Kubernetes manifests using Gator and Datree CLI utilities
=> Add kube-manifests-validation image

.gitlab-ci.yml
Fix kube-manifests-validation image build context
=> Fix kube-manifests-validation image build context

dockerfiles/kube-manifests-validation/Dockerfile
Add Vault to kube-manifest-validation image as it is required in CI pipelines
=> Add Vault to kube-manifest-validation image

dockerfiles/ci-unified/Dockerfile
Will be used by https://github.com/paritytech/polkadot-sdk/issues/1652
=> feat(ci-unified): install musl rust toolchain

dockerfiles/ci-unified/Dockerfile
CI-Unified: Add mdbook-admonish and fix estuary installation (--locked)
=> CI-Unified: Add mdbook-admonish and fix estuary installation

.gitignore, .gitlab-ci.yml, dockerfiles/db-dumper/Dockerfile, dockerfiles/db-dumper/README.md, dockerfiles/db-dumper/app.py, dockerfiles/db-dumper/requirements.txt, dockerfiles/ws-health-exporter/requirements.txt
Changes:
*  new `db-dumper` image was added, check the `dockerfiles/db-dumper/README.md`
* `xbuilder-aarch64-unknown-linux-gnu` image was fixed in `.gitlab-ci.yml`
* `venv` folder was added to `.gitignore`
=> db-dumper was added

dockerfiles/substrate-session-keys-grabber/grabber.py
fix beefy key discovery, find longer sessionkey first.
=> Fix beefy key support

dockerfiles/ansible/Dockerfile
=> update ansible baseimage

dockerfiles/ansible/Dockerfile
For GCP dynamic inventory authentication.
https://github.com/paritytech/devops/issues/3011
=> add google-auth to ansible image

dockerfiles/ci-unified/Dockerfile
Added versioning for rustc-rv32e-toolchain
=> [ci-unified] Add versioning to riscv toolchain

.gitlab-ci.yml
cc https://github.com/paritytech/ci_cd/issues/925
=> Publish ci-unified to GCP Artifact Registry

.gitlab-ci.yml
update helm, helm-secrets and vals for kubetools:helm3 CI image
=> update helm, helm-secrets and vals

.gitlab-ci.yml
cc https://github.com/paritytech/ci_cd/issues/939
=> Push ci-unified to ci project registry

dockerfiles/ci-unified/Dockerfile
add `codecovcli` (cli.codecov.io) in addition to `codecov uploader` (uploader.codecov.io) to ci-unified image
=> add codecovcli for ci-unified

dockerfiles/ci-unified/Dockerfile
update forklift to forklift 0.13.2
fixed 403 errors handling
=> ci-unified forklift 0.13.2
