install-parity.sh

The finish message currently says:
```
==> Run `parity -j` to start the Parity Ethereum client.
```
The `-j` can be removed now that JSON-RPC is enabled by default (as of [this commit](https://github.com/ethcore/parity/commit/4dd63c81a63ae8a6bea5183404ecdf224ed5db2a)).

Remove `-j` from finish message

---

docker-files-for-Gitlab-CI-rust/cross/snapcraft/Dockerfile

fixes https://gitlab.parity.io/parity/parity/-/jobs/59791/raw
Traceback (most recent call last):
File "/usr/bin/snapcraft", line 32, in <module>
obj=dict(project=snapcraft.ProjectOptions()))
File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3/dist-packages/click/core.py", line 675, in main
_verify_python3_env()
File "/usr/lib/python3/dist-packages/click/_unicodefun.py", line 119, in _verify_python3_env
'mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Either run this under Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.
This system supports the C.UTF-8 locale which is …

fix snapcraft build failing because of UTF-8 error

---

get-parity.sh

1) Use debian package on debian derived systems instead of ubuntu package
2) No longer depend on the snap package being present from the vanity service
3) Attempt an rpm install if rpm is found (currently only a centos package is built).

Various updates for linux installer.

---

get-parity.sh

* determine (linux)distro now done through '/proc/versoin' instead of 'lsb_relaease'
* existence of rpm/dpkg binaries no longer used as criteria.
* new variable `LIBSSL={undef|10}` introduced 
* tested with:  centos7, RHEL7.3, debian8, debian9, ubuntults-16.4, SLES12, open-suse-leap

changed method of detecting the linux distribution

---

get-parity.sh

This will go along with a PR in the vanity-service to switch to sha256.

Also ignore sha256 for darwin builds. 

---

get-parity.sh

Can match two instances if another packages sha256sum includes "deb"

Specify actual amd64 package

---

docker-files-for-Gitlab-CI-rust/cross/snapcraft/Dockerfile

I'm not exactly sure whether this helps but dist-upgrading snapcraft in the image creation seems to pull an incompatible version of snapcraft.
https://packages.ubuntu.com/search?keywords=snapcraft
should fix https://gitlab.parity.io/parity/parity-ethereum/-/jobs/97863
any comments welcome

don't dist-upgrade snapcraft's docker image

---

docker-files-for-Gitlab-CI-rust/rustup/Dockerfile

In order to [build substrate, we now need clang to parse headers of the internal rocksdb](https://github.com/paritytech/substrate/pull/1207). This adds the missing dependencies (tested locally) [so that our CI](https://gitlab.parity.io/parity/substrate/-/jobs/111558) passes again.
A review, merge and push of the `nightly`-tagged container would be highly appreciated!

Add clang dependency to docker build container

---

get-substrate.sh

Hi
To pull in the latest beta release and also the improvements to `substrate-up` I executed `curl https://getsubstrate.io -sSf | bash` again.
Everything went fine, except that `subkey` and `substrate` where not updated because I already had them installed before.
```sh
Updating git repository `https://github.com/paritytech/substrate`
Installing subkey v0.1.0 (https://github.com/paritytech/substrate#9dfe0066)   
error: binary `subkey` already exists in destination as part of `subkey v0.1.0 (https://github.com/paritytech/substrate#0370a157)`
Add --force to overwrite
Updating git repository `https://github.com/paritytech/substrate`
Installing substrate v0.9.0 (https://github.com/paritytech/substrate#9dfe0066)
error: binary `substrate` already exists in destination as part of `substrate …
```

get-substrate.sh: force the (re)installation of subkey and substrate

---

docker-files-for-Gitlab-CI-rust/parity-eth-linux-ci/Dockerfile

- should autoupdate when `rust:slim` does,
- `ubuntu:xenial` based,
- with `sccache` which will allow to proceed with caching between jobs,
- new `label`s to better understand what happens.
Tested, 
- able to build, 
- able to launch in virgin `ubuntu:xenial`.
offer to use this container before we will transfer to static linker.

Xenial rust autoupdate

---

get-substrate.sh

`--fast` flag skips the `cargo install` of `substrate` and `subkey`

Add a fast flag option to get-substrate

---

docker-files-for-Gitlab-CI-rust/parity-eth-linux-ci/Dockerfile

no need to pre-download repositories, gitlab docker runner can cache them.

Upgrading docker builder

---

docker-files-for-Gitlab-CI-rust/parity-eth-linux-ci/Dockerfile
docker-files-for-Gitlab-CI-rust/parity-eth-linux-docs/Dockerfile
docker-files-for-Gitlab-CI-rust/substrate-linux-ci/Dockerfile

Parity-ethereum build image:
- new notifier image (official nightly)
- corrected descriptions (is it ok I mention private repo here?)
- beta and nightly Rust added to reintroduce beta and nightly tests
- new cache location to support shared runners
- removed docks dependencies
Parity-ethereum docs image:
- appears
All images will fail during run if errors occurred.

Dockerfile for docs

---

get-substrate.sh

Fixes https://github.com/paritytech/scripts/issues/67
Tested on OSX
Rather than directly doing `cargo install` from a git repo, I clone the repo into a temporary directory, compile wasm, then `cargo install` from the path.

Update script to support compiling wasm before install

---

get-substrate.sh

@xlc we need this in order to install the new script

Add support for `polkadot-*` names scripts from substrate-up

---

docker-files-for-Gitlab-CI-rust/shasper-ci/Dockerfile

inherits from substrate's Ci dockerfile, tested and working.

dockerfile for shasper ci

---

.gitlab-ci.yml

- fix wrong dir for `rust-parity-ethereum-build`
- new name and dir for ex-`parity-substrate-builder`, now `rust-builder`, the universal image for substrate-based stuff
- fix for `$CONTAINER_DATE_TAG`
The idea is to bring the order to the repository.
`$CI_JOB_NAME` should match an image name (without a tag), Dockerfile dir and a variable for launching the schedule.
This is not the final change, it will require further renaming if the images and their dirs.
Renaming will be according the naming rules, and the documentation will follow.
Also, each Dockerfile will have the metadata and it also will be described in the doc.
As we decided about the design, all the docker images should have tags `short-sha` or `short-sha+date` and be pulled everywhere by the `latest` default tag. It will be …

CI simplification I

---

docker-files-for-Gitlab-CI-rust/rust-builder/Dockerfile

- parity/rust-builder is now based on official rust image
- substrate, shasper and polkadot tests and builds have passed
- shows versions of rust and rustc to the build log

rust-builder update

---

polkasync/deployment.yaml

Fix issue:
```
Exception happened during processing of request from ('127.0.0.1', 53474)
Traceback (most recent call last):
File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
self.finish_request(request, client_address)
File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
self.handle()
File "/usr/lib/python3.6/http/server.py", line 418, in handle
self.handle_one_request()
File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
method()
File "dotexporter.py", line 73, in do_GET
if …
```

Fix syntax for /health check

---

.gitlab-ci.yml
dockerfiles/awscli/Dockerfile
dockerfiles/parity-ci-android/Dockerfile
dockerfiles/parity-ci-android/README.md
dockerfiles/parity-ci-arm64/Dockerfile
dockerfiles/parity-ci-arm64/README.md
dockerfiles/parity-ci-armhf/Dockerfile
dockerfiles/parity-ci-armhf/README.md
dockerfiles/parity-ci-docs/Dockerfile
dockerfiles/parity-ci-i386/Dockerfile
dockerfiles/parity-ci-i386/README.md
dockerfiles/parity-ci-linux/Dockerfile
dockerfiles/parity-ci-linux/README.md

All the images which are used in parity-ethereum build process are now being published to our Gitilab docker container registry.
These images now are making use of `sccache` with Redis to avoid the data race condition when pruning old cache pieces.
Metadata was also edited to show the current addresses of the images.

add to sccache features redis

---

get-substrate.sh

This changes the `get-substrate.sh` script to automatically install add the `wasm32` target to rust nightly, and installs `wasm-gc`.
This means we don't need to call `init.sh` anymore for new users as this already does those steps for them.

Remove need for `init.sh` script in `get-substrate.sh`

---

dockerfiles/parity-ci-android/Dockerfile
dockerfiles/parity-ci-arm64/Dockerfile
dockerfiles/parity-ci-armhf/Dockerfile
dockerfiles/parity-ci-i386/Dockerfile
dockerfiles/parity-ci-linux/Dockerfile
dockerfiles/rust-builder/Dockerfile

Painlessly shrinks every `$CARGO_HOME` for >250M and every installed toolchain by >300M

shrink service images

---

dockerfiles/parity-ci-linux/Dockerfile

`clang-8` is needed for `libclang` to install a newer version of `rocksdb`

clang 8 is needed for libclang to install a newer ver of rocksdb

---

dockerfiles/tools/Dockerfile

At least one script I've written requires bash-specific features. It would be useful to be able to make use of this docker image since it also contains lots of tools I regularly make use of

Add bash to the tools Docker image

---

get-parity.sh

Add error if the user selects 'beta' as their release track, and exit immediately.

Remove 'beta' track from get-parity.sh

---

get-parity.sh

We released v2.7.1, so we need to revert the reverts that removed the beta track and version bump (and actually then just bump to v2.7.1).

Revert revert v2.7.0 and beta

---

dockerfiles/ink-ci-linux/README.md

Also the
> [Click here](https://registry.parity.io/parity/infrastructure/scripts/ink-ci-linux) for the registry.
link is broken and should be fixed in a follow-up PR.

Update README title

---

get-parity.sh

Alerts users that parity-ethereum is now open-ethereum and provides a link to the new location

Add deprecation message to get-parity.io

---

dockerfiles/base-ci-linux/Dockerfile
dockerfiles/rust-builder/Dockerfile

After refusing to support scripts for the Open-Ethetreum build, we can use the standard installation, since there are no special requirements for the cmake version now

Installing cmake from the distribution

---

dockerfiles/ink-ci-linux/Dockerfile

clippy bug is fixed, workaround is not needed anymore.

Update ink CI image

---

dockerfiles/base-ci-linux/Dockerfile
dockerfiles/rust-builder/Dockerfile
dockerfiles/substrate-ci-linux/Dockerfile

fix `wasm-bindgen-cli` installation trouble; 
add grumbles from #161: 
better curling, 
clang linking

substrate ci images fixes

---

dockerfiles/rust-builder/Dockerfile
dockerfiles/rust-builder/README.md
dockerfiles/substrate-ci-linux/Dockerfile
dockerfiles/substrate-ci-linux/README.md

Adds `cargo-deny` to substrate CI images.
(probably later it would make sense to add it to `base-ci-linux`)

add cargo-deny to substrate images

---

dockerfiles/ink-ci-linux/Dockerfile

The `2020-04-07` nightly release contains all the required tools:
https://rust-lang.github.io/rustup-components-history/

ink!: update Rust version to nightly-2020-04-06

---

get-substrate.sh

this is fix of possible typo. upgrade of everything shouldn't be necessary - updating casks should be enough to get fresh brews for substrate dependencies.

don't upgrade every brew package

---

dockerfiles/ink-ci-linux/Dockerfile

fixes nightly base to install wasm target
fail on errors, not set vars and trace level of script execution

fix ink! dockerfile

---

.gitlab-ci.yml

Before v13 we have to move from using `only/except` with templates, so trying to do it I stumbled upon a bug that their template [uses](https://gitlab.com/gitlab-org/gitlab/-/blob/68ba7914479b56bb04f5737f6e410772b3f70812/lib/gitlab/ci/templates/Security/Container-Scanning.gitlab-ci.yml#L28) `only`.
Had to workaround their [official](https://docs.gitlab.com/ee/user/application_security/container_scanning/#configuration) suggestion.

Prep to deprecation in GitLab 13

---

dockerfiles/ink-ci-linux/Dockerfile

Updates the Rust nightly version of the ink! dockerfile to `2020-05-30`.

ink!: Update Rust nightly version

---

dockerfiles/base-ci-linux/Dockerfile
dockerfiles/base-ci-linux/README.md
dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/ink-ci-linux/Dockerfile
dockerfiles/substrate-ci-linux/Dockerfile

- temporary `sccache` is installed from the master branch, it contains a fix we need
Accidentally did some optimizations:
- moved to `buster-slim` base. Not much thinner, but the attack surface is lower.
- added minimal profile, so rust doesn't take all the default components, we were installing them anyways. This decreases each toolchain by ~50Mb.
- moved `nightly` Rust installation to the images that actually using it
- started changing labels to the "best practices" recommendations
- some lints
Tested on [Substrate](https://gitlab.parity.io/parity/substrate/pipelines/95067), [ink!](https://gitlab.parity.io/parity/ink/pipelines/94949) and [pallet-waterfalls](https://gitlab.parity.io/parity/pallet-contracts-waterfall/-/jobs/536719) CIs.
`base-ci-linux` image size went down from 475Mb to …

Override base image to use fixed sccache before its release

---

.gitlab-ci.yml
dockerfiles/ci-linux/Dockerfile
dockerfiles/ci-linux/README.md

and temporary publishing to the old `parity/rust-builder:latest` image.

Rename substrate-ci-linux; 

---

dockerfiles/base-ci-linux/Dockerfile

Not sure why `jq` wasn't already in our base image, but I think it should be. It's a small package and is super useful to have available in any CI job where we might want to read stuff from Github.
Ref: https://github.com/paritytech/polkadot/pull/1455#issuecomment-662490147

Add jq to base-ci-linux

---

dockerfiles/awscli/Dockerfile

Due to [this](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1550) bug in gitlab-runner, a non-POSIX feature is used even when the shell is not `bash`. I {am using|will use} this image to push release-candidate builds to S3 on the cleanroom (see [this](https://gitlab.parity.io/s3krit/cleanroom/-/tree/gitlab-runner/ansible/roles/polkadot/files/gitlab-runner) branch or just ask me if you're curious about the progress of that), so run into this issue.
The actual issue is with the [`set -eo pipefail`](https://gitlab.com/gitlab-org/gitlab-runner/-/blob/master/shells/bash.go#L224) - some POSIX shells *do* seem to support this (or at least don't error when setting it), such as busybox's shell. So far I've only ran into `dash` that will actually error when attempting it.

Add bash to awscli image

---

dockerfiles/awscli/Dockerfile
dockerfiles/base-ci-linux/Dockerfile
dockerfiles/chaostools/Dockerfile
dockerfiles/ci-linux/Dockerfile
dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/contracts-ci-linux/README.md
dockerfiles/ink-ci-linux/Dockerfile
dockerfiles/ink-ci-linux/README.md
dockerfiles/kubetools/Dockerfile
dockerfiles/redis-exporter/Dockerfile
dockerfiles/terraform/Dockerfile
dockerfiles/tools/Dockerfile

The most important change is that rustup searches the latest common `nightly` Rust version for the list of the given components. This removes the need in the frequent PRs to update the nightly version for `ink` or `contracts`.
Second valuable point is that previously I was removing the build-in docs and help from each toolchain, and it was worth it. The economy was ~150 Mb per a toolchain. But it potentially lead to some troubles with `rustup`. AAMF it couldn't update and do things with toolchains due to it wanted to remove the old stuff and couldn't find it. Nevertheless we are not updating stuff in the images, it could potentially lead to some other wierd stuff. Thankfully, `--profile minimal` does nearly the same.
Also I realized that `cargo install` within the image build time …

new nightly installation, various optimizations and lints

---

dockerfiles/base-ci-linux/Dockerfile

Still waiting until https://github.com/mozilla/sccache/issues/663 will be merged, having
```
Compiling futures-channel v0.3.5
error[E0514]: found crate `hash_db` compiled by an incompatible version of rustc
--> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/trie-root-0.16.0/src/lib.rs:41:9
|
41 | pub use hash_db::Hasher;
|         ^^^^^^^
|
= help: please recompile that crate using this compiler (rustc 1.49.0-nightly (b20253260 2020-11-01))
= note: the following crate versions were found:
crate `hash_db` compiled by rustc 1.49.0-nightly (ffe52882e 2020-10-30): /builds/parity/substrate/target/release/wbuild/target/wasm32-unknown-unknown/release/deps/libhash_db-7abf16653d25fc04.rmeta
```
randomly.

change (dockerfile): return to workaround sccache's bug

---

dockerfiles/ink-ci-linux/Dockerfile

Closes paritytech/ci_cd#53
- add the latest `cargo-contract` binary from master (to be pinned later)
Now, when GitLab stores the latest artifact for the branch, this method can be used sustainably.

change (dockerfile): add latest contract

---

dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/contracts-ci-linux/README.md
dockerfiles/ink-ci-linux/Dockerfile

> Can't be merged until https://github.com/paritytech/canvas-node/issues/21 is resolved, this will break the `test` job in `cargo-contracts` CI. Other than that, `fmt` and `build` are successful.
Temporary workaround: https://github.com/paritytech/cargo-contract/pull/114
- `solang` update to `v0.1.2`, newer versions did not work
- `canvas`-node binary included as an artifact from the latest master
- `clang-8` set as a linker
- `python3` set as default
Closes paritytech/ci_cd#1 
Closes paritytech/ci_cd#18

Update solang and canvas-node in contracts CI image

---

.gitlab-ci.yml

Contracts CI image is now tested against contract code every time the image is updated (nightly).
Pipeline 
1. Scripts CI builds `contracts-ci-linux:staging`
2. Runs container scan and
Triggers the downstream Contracts CI pipeline for the master branch [to be executed in](https://gitlab.parity.io/parity/cargo-contract/-/jobs/732567#L4) `contracts-ci-linux:staging` image
3. If the test is green, `contracts-ci-linux:staging` gets published as `contracts-ci-linux:production`
In the other case, It's easier for the developers to see the failed pipeline in their own CI rather than look into this one (which no one does).
A good example of the pipeline: https://gitlab.parity.io/parity/infrastructure/scripts/-/pipelines/115699
Companion PR: https://github.com/paritytech/cargo-contract/pull/115

Trigger contracts CI to test the image against master

---

.gitlab-ci.yml

Same as in https://github.com/paritytech/scripts/pull/238 but for `ink` and `sccache` CI images
CI images are now tested against their target code every time the image is updated (nightly).
Pipeline example
1. Scripts CI builds `contracts-ci-linux:staging`
2. Runs container scan and
Triggers the downstream Contracts CI pipeline for the master branch [to be executed in](https://gitlab.parity.io/parity/cargo-contract/-/jobs/732567#L4) `contracts-ci-linux:staging` image
3. If the test is green, `contracts-ci-linux:staging` gets published as `contracts-ci-linux:production`
In the other case, It's easier for the developers to see the failed pipeline in their own CI rather than look into this one (which no one does).
A good example of the pipeline: …

Nightly tested ci images for sccache and ink

---

.gitlab-ci.yml

Recent docker changes have broken our images building. Docker breaks pretty much things lately, so I decided to stay away from it.
First I tried with `kaniko`, and it works well, but decided to move to `buildah` since they are closer to what we do.
The downside is I've broken the [image scanning](https://github.com/optiopay/klar/issues/140), this is something connected with `buildah`'s image manifest version and format.
I'll describe the important changes, because right now all the GitLab CI jobs, those building images are not working. So please take care of your repositories:
- variables starting with `DOCKER*`, such as `DOCKER_HOST`, `DOCKER_DRIVER` are no longer needed, but login creds to dockerhub are certainly needed
- `buildah` uses more transports than `docker`, it means that with …

Buildah to build images

---

.gitlab-ci.yml

- fixes `buildah bush`, apparently it couldn't push several tags within one command
- removes `--squash`, is wins in the final image size, but makes it one layer, hence unable to reuse the base image, looses in download time.

remove squash and fix buildah push

---

dockerfiles/ci-linux/Dockerfile

Adds `diener` to the CI image.
Now it needs to be removed from https://github.com/paritytech/substrate/blob/3c531e291fcc2c315abd3dcf436c487cdd91bd25/.maintain/gitlab/check_polkadot_companion_build.sh#L44

dockerfile: add diener

---

.gitlab-ci.yml

FYI: new scanning job requires both `IMAGE_NAME` and `IMAGE_TAG` set in [schedule](https://gitlab.parity.io/parity/infrastructure/scripts/-/pipeline_schedules). I've set them for all schedules we have.
Since the official GitLab scanner [fails](https://gitlab.parity.io/parity/infrastructure/scripts/-/jobs/782258#L971) to scan the images we push to dockerhub by buildah and GitLab is knowingly [slow](https://gitlab.com/gitlab-org/gitlab/-/issues/294421#note_472133709) in fixing everything, I've decided to introduce an alternative scanner. 
Did a little research and `trivy` is better than `clar`/`clair`/`klar` and, what's important, **is supported**.
It's also good at checking [various](https://gitlab.com/gitlab-org/gitlab/-/issues/294421#note_472133709) lockfiles, i.e. Rust, node.js, python, …

trivy container scanner v1

---

.gitlab-ci.yml

For the better maintainability and observability it's good to trigger the repo itself, so developers will know what stops the CI image from being updated.
Overrides `RUSTFLAGS` to avoid failures on `-Dwarnings`, in this case it's not needed.
Merge after `CI_IMAGE` is introduced to substrate CI repo.

CI: trigger substrate CI on image test

---

dockerfiles/ci-linux/Dockerfile
dockerfiles/ci-linux/README.md

- `cargo-deny` [issue](https://github.com/EmbarkStudios/cargo-deny/issues/331#issuecomment-778617026) was fixed really fast
- better to have `mdbook` installed in the CI image, to fit the containers security policy: https://github.com/paritytech/polkadot/blob/e47912494b8d28a48be6a088c48ab9bf4e2205e1/.gitlab-ci.yml#L208

dockerfiles: restore cargo-deny as it's fixed, add mdbook

---

dockerfiles/base-ci/Dockerfile
dockerfiles/base-ci/README.md
dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/contracts-ci-linux/README.md
dockerfiles/ink-ci-linux/Dockerfile
dockerfiles/ink-ci-linux/README.md

- new `base-ci`, now powered by `ubuntu:20.04`
- `contracts-ci-linux` and `ink-ci-linux` are rebased to the new base image
- `contracts-ci-linux` gets `clang10` from ubuntu 
image compiles and works, currently published under `paritytech/contracts-ci-linux:ubuntu` @cmichi please check, I'm not sure what's with `wasm-opt` and if it's still needed.
- pretty much the same with `ink-ci-linux`, unless it's not ready now.

WIP: dockerfiles: new base starts off ubuntu 20.04, ink and contracts CI images inherit it

---

dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/contracts-ci-linux/README.md

dockerfiles: undelete python3 from contracts image

---

dockerfiles/ci-linux/Dockerfile

Pin `wasm-bindgen-cli` according to https://github.com/paritytech/substrate/blob/master/bin/node/browser-testing/Cargo.toml#L15

pin wasm-bindgen-cli version in substrate CI

---

.gitlab-ci.yml
dockerfiles/terraform/Dockerfile
dockerfiles/terraform/README.md

The goal of this PR is to add the vault binary to the `paritytech/terraform` image to be able to use the vault client CLI in terraform pipelines in order to retrieve secrets.

dockerfiles: add vault binary in terraform image

---

.gitlab-ci.yml

Allows to build `node-bench-regression-guard` image via the relevant pipeline.

node-bench-regression-guard: ci

---

dockerfiles/ink-ci-linux/Dockerfile
dockerfiles/sccache-ci-ubuntu/Dockerfile

- now it depends on the [common ubuntu base image](https://github.com/paritytech/scripts/tree/master/dockerfiles/ci-linux), hence builds faster and much lighter.
- rust `stable` is the default
- `nightly` is installed with a minimal profile

refactor sccache CI image

---

dockerfiles/ci-linux/Dockerfile

This is required for UI tests.

Install `rust-src` for Substrate CI image

---

.gitlab-ci.yml
dockerfiles/sops/Dockerfile
dockerfiles/sops/README.md

Add a docker image containing sops for encrypting and decrypting secrets contained in files using an encryption-as-a-service provider (KMS) such as Vault.
The vault binary is added for convenience to preform login operations on Vault and get the vault token that will be passed to sops.

dockerfiles: add sops docker image

---

dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/contracts-ci-linux/README.md
dockerfiles/ink-ci-linux/Dockerfile
dockerfiles/ink-ci-linux/README.md

Closes https://github.com/paritytech/ci_cd/issues/121.
I tested it locally via
```
docker build -t contracts-ci 
docker run -it contracts-ci
7ca83609797f:/builds# cargo-contract --version                            
cargo-contract 0.11.1-unknown-x86_64-linux-gnu
```

Remove `--binaryen-as-dependency`

---

dockerfiles/ansible/Dockerfile
dockerfiles/awscli/Dockerfile
dockerfiles/base-ci-linux/Dockerfile
dockerfiles/base-ci/Dockerfile
dockerfiles/ci-linux/Dockerfile
dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/ink-ci-linux/Dockerfile
dockerfiles/ink-waterfall-ci/Dockerfile
dockerfiles/kubetools/Dockerfile
dockerfiles/kubetools/helm3.Dockerfile
dockerfiles/node-bench-regression-guard/Dockerfile
dockerfiles/query-exporter/Dockerfile
dockerfiles/redis-exporter/Dockerfile
dockerfiles/sccache-ci-ubuntu/Dockerfile
dockerfiles/sops/Dockerfile
dockerfiles/terraform/Dockerfile
dockerfiles/tools/Dockerfile

Don't use shortnames, especially with Red Hat containers tools.

Use fully qualified image names in Dockerfiles

---

dockerfiles/ink-waterfall-ci/Dockerfile

Follow-up for https://github.com/paritytech/ink/pull/793.

Integrate `rand-extension` into `ink-waterfall`

---

.gitlab-ci.yml

Resolves paritytech/ci_cd#135.
Reset `REGISTRY_AUTH_FILE` to explicitly tell `buildah` not to request creds for public registries.

Reset REGISTRY_AUTH_FILE when creds are not needed

---

dockerfiles/awscli/Dockerfile
dockerfiles/kubetools/Dockerfile
dockerfiles/kubetools/helm3.Dockerfile
dockerfiles/node-bench-regression-guard/Dockerfile
dockerfiles/query-exporter/Dockerfile
dockerfiles/sops/Dockerfile
dockerfiles/terraform/Dockerfile
dockerfiles/tools/Dockerfile

Relates to paritytech/ci_cd#92.
This PR adds non-root user only for ops tooling images as per my comment [here](https://github.com/paritytech/ci_cd/issues/92#issuecomment-847926377).
Please review the changes. After the merge, I'll rebuild the affected images.

Add non-root user for the ops tooling images

---

dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/ink-waterfall-ci/Dockerfile

`ci-linux` still runs as `root`, so I revert this too until we resolve downstream issues. Failing jobs are mentioned in `TODO` comments.
Why would I do this? Stable Rust has to be updated sometimes and it's not possible to update such "hanging" images while there are unrelated issues.

Temporary switch back to `root` for some images

---

dockerfiles/ci-linux/Dockerfile

As requested by @bkchr. After this merge and consequent `paritytech/ci-linux:production` build:
* Rust stable will be on `1.52.1`
* Rust nightly will be on `2021-04-22`
* `nightly-2021-04-22` toolchain will be symlinked as `nightly` toolchain for seamless interoperability (or do we want to change `+nightly` to `+nightly-2021-04-22` in all relevant CI jobs?)
By the way, is there any other way to alias specific nightlies as "generic" nightly? `ln -s` looks like a hack and I wasn't able to find any info that symlinking toolchains like this is some kind of a proper practice.

Pin Rust nightly to 2021-04-22 for `paritytech/ci-linux`

---

dockerfiles/ci-linux/Dockerfile

Missed one day here with my previous nightly pinning.
`paritytech/ci-linux:9a44d4ec-20210423` (`paritytech/ci-linux:production` before introducing Rust stable `1.52.1`) had nightly `7f4afdf02 2021-04-22`, not `b84932674 2021-04-21`, what I've pinned before.
This PR corrects that. Will rebuild `paritytech/ci-linux:production` after the merge.

Bump nightly to 2021-04-23 for `paritytech/ci-linux`

---

dockerfiles/ci-linux/Dockerfile

Due to changes in companion building in https://github.com/paritytech/substrate/pull/9010 - I need the ability to bump beefy using `diener`, which I added in `v0.4.0`.

bump diener in ci-linux image

---

dockerfiles/ink-ci-linux/Dockerfile
dockerfiles/ink-ci-linux/README.md

adds `llvm-tools-preview` component to ink CI image, to the nightly toolchain. It's needed for MIR source-based Rust coverage instrumentation,

dockerfile: llvm-tools-preview

---

dockerfiles/ci-linux/Dockerfile

`stable` toolchain will be bumped to `1.54.0` implicitly.

Explicitly bump nightly for `ci-linux`

---

dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/contracts-ci-linux/README.md
dockerfiles/ink-waterfall-ci/Dockerfile
dockerfiles/ink-waterfall-ci/README.md

We have migrated the `canvas-node` from a standalone node to a parachain setup. 
The former standalone node can now be found at https://github.com/paritytech/substrate-contracts-node.
The Docker image build will currently fail due to https://github.com/paritytech/ci_cd/issues/189. But the CI's for projects which use `canvas-node` are currently failing anyway, since the parachain setup is not suited for them.

Migrate `canvas-node` to `substrate-contracts-node`

---

dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/ink-ci-linux/Dockerfile

The ink! CI's fail currently because the latest `binaryen` release does not contain a Linux binary (see the linked issue).
This PR fixes this by falling back to the latest release *with a Linux binary*.

Use latest `binaryen` release which contains a Linux binary

---

dockerfiles/ci-linux/Dockerfile

It's used in https://github.com/paritytech/polkadot/pull/3807 and https://github.com/paritytech/substrate/pull/9637 so if they are green, this may be merged.

dockerfiles: update pinned nightly to 2021-09-13

---

dockerfiles/ink-waterfall-ci/Dockerfile

The docker image fails currently to build because of this.

Fix `ink-waterfall-ci` docker image

---

dockerfiles/base-ci-linux/Dockerfile

This will unblock https://github.com/paritytech/substrate/pull/9749 and https://github.com/paritytech/substrate/pull/9721 because we need jq >= 1.6 for them, but Debian buster only has jq 1.5.
For extra context see https://github.com/paritytech/ci_cd/issues/193.
closes https://github.com/paritytech/ci_cd/issues/193

Install jq from Github Releases

---

.gitlab-ci.yml

This PR adds pipeline functionality to retry CI jobs twice in case if it failed due to following reasons:
```yml
- runner_system_failure
- unknown_failure
- api_failure
```
It will increase pipelines resilience against accidental failures like network timeouts etc.

Increase pipelines resilience against accidental failures

---

dockerfiles/ci-linux/Dockerfile

Added stable rustfmt,clippy to `paritytech/ci-linux` image.
Discussion was here: https://github.com/paritytech/jsonrpsee/pull/534

Add rustfmt,clippy to ci-linux for jsonrpsee

---

dockerfiles/ink-ci-linux/Dockerfile

The original issue has been resolved, but the path to the binary in the release changed.
That's why the schedule `ink-ci-linux` Docker job fails since Friday (they published a new release on Friday): https://gitlab.parity.io/parity/infrastructure/scripts/-/jobs/1267123.

Fix path to `wasm-opt` binary in `binaryen` release

---

dockerfiles/cachepot-ci/Dockerfile

Refs paritytech/cachepot#128 paritytech/cachepot#114
Otherwise we can't run sandboxed builds in our dist test suite, see https://gitlab.parity.io/parity/cachepot/-/jobs/1291693#L2738 for example
cc @drahnr

cachepot-ci: Add bubblewrap for dist compiles/tests

---

.gitlab-ci.yml
dockerfiles/benchmarks/.gitignore
dockerfiles/benchmarks/Dockerfile
dockerfiles/benchmarks/README.md
dockerfiles/benchmarks/check_bench_result.py
dockerfiles/benchmarks/push_bench_results.sh
dockerfiles/benchmarks/requirements.txt

This PR adds `paritytech/benchmarks` image.
In the issue https://github.com/paritytech/ci_cd/issues/275 was a request to check benchmarks and create a github issue if they exceeds threshold 20%
I created a script that does that but also decided to put this into a docker image so we can reuse it in other projects

Add benchmarks image

---

dockerfiles/benchmarks/check_bench_result.py

Added function `benchmark_last_sha`.
Previously, if regression was found the issue was created with a text with 2 benchmark results: current and previous. Previous result had a link to last commit sha in the repo. But last benchmark is not always run on the latest commit and between benchmark results can be more than 1 commit, so the right way would be to find a commit with last benchmark related to it. That's why the function is implemented.

add fun benchmark_last_sha

---

dockerfiles/kubetools/helm3.Dockerfile

This is required for running custom Python scripts in Kubernetes CI jobs.

Add python and the kubernetes-python lib to the helm3 image

---

dockerfiles/contracts-ci-linux/Dockerfile

I've added some `dylint` stuff to the `cargo-contract` CI docker image in https://github.com/paritytech/scripts/pull/382. The docker image can't be build currently though: https://gitlab.parity.io/parity/cargo-contract/-/jobs/1376793.
This is due to an ICE in the nightly version of the Rust compiler (https://github.com/rust-lang/rust/issues/93788). Since I need those `dylint` tools now-ish, I would like to temporarily set a fixed Rust nightly version. We can revert this PR once the ICE is fixed.
Let's not go into a discussion of setting a fixed toolchain version now.

Revert me: Set fixed Rust nighly version

---

dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/ink-waterfall-ci/Dockerfile

Building those containers currently fails: https://gitlab.parity.io/parity/infrastructure/scripts/-/jobs/1433766.
```
+ substrate-contracts-node --version
/usr/local/cargo/bin/substrate-contracts-node: 2: Syntax error: newline unexpected
subprocess exited with status 2
```
This is due to the recent `clap` switch/upgrade in Substrate. I've added a commit which filters empty lines from the `--version` output.

Filter empty new lines in `--version` output

---

dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/contracts-ci-linux/README.md

Yesterday I wanted to publish a new release of `cargo-contract` (https://github.com/paritytech/cargo-contract/pull/461), but while doing so I noticed that the publishing failed due to some issues which we notice find before (e.g. missing `include`'s in the `Cargo.toml` and directories no longer being found due to how `CARGO_MANIFEST_DIR` changes when publishing).
Those issues only surface when actually going through the publish process. Some parts of it can be mocked with `cargo package`, but that only covers part of the publishing process.
`cargo-contract` has a bit of an elaborate `build.rs` now and I would like to have a CI stage for this project which spawns a lightweight local registry, publishes to it, installs from it, and does some smoke testing with the installed binary. I want …

Add `estuary` to `contracts-ci-linux`

---

dockerfiles/ink-ci-linux/Dockerfile
dockerfiles/ink-ci-linux/README.md

Only noticed now (after the `cargo-contract` 0.18.0 release today) that those are missing in the ink! CI.

Install `cargo-dylint` and `dylint-link` in `ink-ci-linux`

---

.gitlab-ci.yml
dockerfiles/debian10/Dockerfile
dockerfiles/debian10/README.md
dockerfiles/molecule/Dockerfile
dockerfiles/molecule/README.md

`molecule` and `debian10` images was added. This images will be used in ansible molecule CI.

Add molecule docker images

---

.gitlab-ci.yml
dockerfiles/smart-bench-ci/Dockerfile
dockerfiles/smart-bench-ci/README.md

Needed for https://github.com/paritytech/ci_cd/issues/357.
I copied the `ink-waterfall-ci` image and threw a lot of stuff out.

Add simple initial docker image for `smart-bench`

---

.gitlab-ci.yml

The PR fixes path for triggered projects since they have a new location. Also I added jobs for `parity-scale-codec` in order to update the image on regular basis.

Fix projects paths and add job parity-scale-codec

---

dockerfiles/ci-linux/Dockerfile

Part of:
https://github.com/paritytech/ci_cd/issues/359
Needed for:
https://github.com/paritytech/polkadot/pull/5282
https://github.com/paritytech/substrate/pull/11138

Update rust nightly ci-linux

---

dockerfiles/kubetools/helm3.Dockerfile

The kubectl version is outdated. All of the kube cluster that are running is at 1.21.10.

Bump Kubectl version

---

.gitlab-ci.yml

Trivy is going to pull images from public registries, so no auth is needed. See https://gitlab.parity.io/parity/mirrors/scripts/-/jobs/1588328

CI: fix trivy

---

dockerfiles/ci-linux/Dockerfile

PR adds cargo-nextest to the `ci-linux` image
Part of https://github.com/paritytech/ci_cd/issues/334

ci-linux - add cargo-nextest to the image

---

dockerfiles/ws-health-exporter/Dockerfile

Update Dockerfile to match gitlab-ci context path. It is set to `dockerfiles` directory which fails the build with the previous setup.

Update Dockerfile to match gitlab-ci context path

---

dockerfiles/contracts-ci-linux/Dockerfile

Attempt to fix [broken docker build](https://gitlab.parity.io/parity/mirrors/scripts/-/jobs/1661549).
`cargo install` no longer works out of the box without (I think) a build of[ `llvm-project` ](https://github.com/hyperledger-labs/solang/blob/main/.github/Dockerfile#L11) which adds the `Driver.h` file to the path for the [linker include](https://github.com/hyperledger-labs/solang/blob/c046e64db8890d0db83d65cbfd2bb0918b7ffd1e/src/linker/linker.cpp#L2).
```
cargo:warning=src/linker/linker.cpp:2:10: fatal error: 'lld/Common/Driver.h' file not found
cargo:warning=#include "lld/Common/Driver.h"
```
A rudimentary [search](https://github.com/search?p=2&q=org%3Aparitytech+solang&type=Code) appears that this is not used anywhere currently by this image.
If this is required anywhere in CI, I …

contracts-ci: remove solang

---

dockerfiles/contracts-ci-linux/Dockerfile

The download URL is incorrect. In current `:latest` and `:production` images the `substrate-contracts-node` file is just the HTML error page instead of the actual binary :grin: 
I will use this in solang integration tests

contracts-ci-linux: fix substract-contracts-node binary download URL

---

dockerfiles/ci-linux/Dockerfile

Needed for https://github.com/paritytech/substrate/pull/11903 and https://github.com/paritytech/ci_cd/issues/535

[ci-linux] update nightly to 2022-07-25

---

dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/ink-ci-linux/Dockerfile

Right now things keep breaking so we haven't been able to produce a `production` Docker
image for a while. Pinning the nightly will help us fix the CI so that we can publish
this new image.

Pin ink! related nightlies to 2022-07-28

---

dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/ink-ci-linux/Dockerfile

As part of the ink! CI we have some stages which use the `+nightly`
calling convention. These ended up failing since we didn't have a
nightly toolchain, only a `+nightly-zzzz-yy-xx` one.
In the past we've had both toolchains installed, but this meant possible
inconsistencies when running those stages.
This takes inspiration from the base CI Dockerfile.

Alias pinned nightly to "normal" nightly

---

dockerfiles/ink-waterfall-ci/Dockerfile

No idea why this only happens now. Our `base-ci-linux` image contains it by default.
Our waterfall Docker build currently fails with
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotFound, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): No such file or directory (os error 2)" }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.34.0/build.rs:30:6
```
https://gitlab.parity.io/parity/mirrors/scripts/-/jobs/1751668

Install `protoc` for `ink-waterfall`

---

dockerfiles/ci-linux/Dockerfile
dockerfiles/ci-linux/README.md

As discussed in https://github.com/paritytech/jsonrpsee/pull/860 cargo-hack should be added to `ci-linux`
cc @lexnv

Add cargo-hack to ci-linux

---

dockerfiles/contracts-ci-linux/Dockerfile
dockerfiles/ink-ci-linux/Dockerfile

After https://github.com/paritytech/cargo-contract/pull/698 we're able to build contracts
using the stable toolchain instead of nightly.
This updates our CI images to use stable as the default toolchain.

Use stable toolchain as default for ink! related CI images

---

dockerfiles/ink-ci-linux/Dockerfile

Fixes the failing ink! CI on `master`.
https://gitlab.parity.io/parity/mirrors/ink/-/jobs/1783302

Add `clippy` and `rustfmt` for stable

---

dockerfiles/base-ci/Dockerfile

Relates to https://github.com/paritytech/ci_cd/issues/627.

Add `protoc` to the common base CI image

---

dockerfiles/terraform/Dockerfile

Install `openssh` package to terraform image.

paritytech/ci_cd#583: Add `ssh` command to terraform image

---

dockerfiles/base-ci-linux/Dockerfile
dockerfiles/ci-linux/Dockerfile
dockerfiles/ci-linux/README.md

I suggest to install this tools for the `build-implementers-guide` job in polkadot pipeline
cc https://github.com/paritytech/polkadot/pull/6216

Add mdbook utils to ci-linux

---

.gitlab-ci.yml

Bump kubectl to 1.24 as it has some new features. I personally require this to work:
`kubectl wait --for=jsonpath='{.status.replicas}'=0 --timeout=-1s sts/$STS_NAME`
which is not available in 1.22. 
1.24 kubectl should be compatible with both 1.22 and 1.23 versions of the server though we'll preserve 1.22 remote tag.

Bump kubectl to 1.24

---

dockerfiles/ink-ci-linux/Dockerfile
dockerfiles/ink-ci-linux/README.md

Add cargo nextest Install to improve test performance in DockerFile, 
First Part of these CI changes for ink!, https://github.com/paritytech/ink/issues/1474

Add cargo nextest installation

---

dockerfiles/base-ci-linux/Dockerfile
dockerfiles/base-ci-linux/README.md
dockerfiles/utility/base-ci-linux-config

We have linker failures in the Substrate CI most possibly related that `clang-13` is too old for currently used Rust versions. This PR bumps `clang` from `13` to `14` for the base image and the dependent `ci-linux` image.

Use `clang-14` for `paritytech/base-ci-linux`

---

dockerfiles/base-ci-linux/Dockerfile
dockerfiles/base-ci-linux/README.md
dockerfiles/utility/base-ci-linux-config

`clang` used `ld` as a linker instead of `lld` whole this time. This PR fixes that and also downgrades LLVM and `clang` back to 14.
Superseeds #490 and relates to #488.

Use LLVM's lld instead of GNU's ld

---

dockerfiles/xbuilder-aarch64-unknown-linux-gnu/Dockerfile
dockerfiles/xbuilder-aarch64-unknown-linux-gnu/README.md

A new Docker image to support cross building binaries for `aarch64-unknown-linux-gnu` (arm64).
See also https://github.com/paritytech/polkadot/pull/6108
I pushed an image to `chevdor/parity-xbuilder-aarch64-unknown-linux-gnu`. This image will however **not** be able to build polkadot master until https://github.com/paritytech/polkadot/pull/6108 is merged. In the meantime, the [branch of the PR](https://github.com/paritytech/polkadot/tree/wk-221004-target-aarch64-apple-darwin) can be built.
Production builds are done using the `production` profile but for testing, `release` is slightly faster to build.
```
IMAGE=chevdor/parity-xbuilder-aarch64-unknown-linux-gnu
time docker run --rm --name builder  -v $PWD:/app ${IMAGE} --package polkadot --profile release
```

Add new image: `xbuilder-aarch64-unknown-linux-gnu`

---

dockerfiles/node-wrk/Dockerfile

Current version doesn't have `yarn`. Needed for https://github.com/paritytech/ci_cd/issues/739

Update node version in node-wrk image

---

.gitlab-ci.yml
dockerfiles/releng-scripts/.dockerignore
dockerfiles/releng-scripts/Dockerfile
dockerfiles/releng-scripts/README.md
dockerfiles/releng-scripts/build.sh

As discussed with @alvicsam, this PR adds a new Dockerfile as well as the script required to build the image.
The `build.sh` script mainly git clones the releng-scripts repo in order to build the image.
Testing can be done as mentioned in https://github.com/paritytech/releng-scripts/pull/34

Add new Docker image for the `releng-scripts` repo

---

dockerfiles/ink-waterfall-ci/Dockerfile

The cause of this [fail](https://gitlab.parity.io/parity/mirrors/scripts/-/jobs/2465875) is that `examples` now moved to `integration-tests` in ink! repository.
This patch is intended to fix it

ink-waterfall-ci image: fix link to integration tests 

---

dockerfiles/ci-linux/Dockerfile

2023-03-16 is broken,
cf https://github.com/rust-lang/rust/issues/109199

ci-linux: revert rust nightly to 2023-03-15

---

dockerfiles/ci-linux/Dockerfile

The current nightlies introduce a ton of new clippy warnings, and their clippy is also mildly buggy, which makes it a pain to fix everything.
Given we're hopefully getting rid of the nightly toolchain very soon anyway, let's just revert it for now rather than sinking an inordinate amount of effort into the bump.

ci-linux: Revert nightly rust to 2022-11-16

---

dockerfiles/ci-linux/Dockerfile

We've stopped using nightly rust in our substrate/polkadot/cumulus pipelines except for `cargo fmt`, cf https://github.com/paritytech/ci_cd/issues/767

feat(ci-linux)!: drop unneccessary nightly components

---

dockerfiles/ci-linux/Dockerfile

See https://github.com/paritytech/pipeline-scripts/issues/97#issuecomment-1420642980 for context.
Tested through https://github.com/paritytech/substrate/pull/13324 (see https://github.com/paritytech/scripts/pull/506#issuecomment-1420694711).
closes https://github.com/paritytech/pipeline-scripts/issues/97

Update diener version

---

dockerfiles/bridges-ci/Dockerfile

Related to: https://github.com/paritytech/parity-bridges-common/issues/2035
The bridges builds are failing lately. For example: https://gitlab.parity.io/parity/mirrors/parity-bridges-common/-/jobs/2683372
With error message:
```
Rust WASM toolchain not installed, please install it!
```
That's because the `wasm32-unknown-unknown` is not installed for the stable rust toolchain

Fix bridges build

---

.gitlab-ci.yml
dockerfiles/github-gh-cli/Dockerfile
dockerfiles/github-gh-cli/README.md

This PR adds a Docker image which contains `git` and `gh` so that it could be used on the cleanroom for doing some github stuff like PR creation from the command line. 
As an example, it will be needed for the release  automation of the `parity-keyring`

add docker image for the GitHubClI tools

---

.gitlab-ci.yml

The .push_to_production script was inadvertently broken in #550. This pull command is neccessary because the .push_to_production jobs don't run in the same environment that originally built the staging image, and thus doesn't have a local copy of the staging image available.

Fix .push_to_production job template

---

.gitlab-ci.yml
dockerfiles/ci-unified/Dockerfile
dockerfiles/ci-unified/README.md
dockerfiles/ci-unified/cargo-config

I want to try to gradually replace all our CI images with a single one that is built from the single source of truth, tagged as `<distro codename>-<rust version>`, plus an additional `<distro codename>` tag. I don't think that image size matters, if we'll also push the image to our internal registry located closely to the CI runners or just start proxying the Docker Hub upstream.
What this PR introduces right now:
* New `ci-unified` image that combines `base-ci-linux` and `ci-linux` (will absorb other images later)
* Bump the base image to Ubuntu 22.04 (needed for my Firebuild tests, could be downgraded back to `stretch` if there will be no success with Firebuild)
* Bump LLVM to 15 and allow upping its version via a single change to the relevant `ARG`
* Pin stable Rust to bump it …

Introduce unified CI image

---

.gitlab-ci.yml
dockerfiles/lz4/README.md

`changes:` in the `.docker_build_pr` hidden job wasn't working properly, resulting in creating `.docker_build_pr` templated job for each defined image which gave tremendous overhead. This PR fixes that.

Fix broken `changes:` behavior

---

.gitlab-ci.yml
dockerfiles/debian11/Dockerfile
dockerfiles/debian11/README.md

The debian 11 docker image was added because we need it to run new versions of node binaries.

debian 11 docker image was added

---

dockerfiles/ci-linux/Dockerfile

Projects with substrate version less than 0.9.42 need wasm target installed into nightly toolchain. Though a project itself can be built on stable, the wasm-builder [searches](https://github.com/paritytech/substrate/blob/98f2e3451c9143278ec53c6718940aeabcd3b68a/utils/wasm-builder/src/lib.rs#L208) for the latest nightly toolchain with wasm target programmatically. It was fixed [here](https://github.com/paritytech/substrate/pull/13580) and released only in 0.9.42, so all versions before that need to have a nightly (even not active) toolchain with wasm target installed.
We are currently facing an issue with benchmarking Trappist via command bot. Trappist is built on v0.9.37. There are other projects suffering from this as well.

Install wasm target into nightly toolchain

---

dockerfiles/ci-linux/Dockerfile

There is a [known problem](https://stackoverflow.com/questions/75955457/substrate-node-template-cannot-create-a-runtime-error-othercannot-deserialize) with wasm compilation on the latest rust nightly. For example, [this job](https://gitlab.parity.io/parity/mirrors/trappist/-/jobs/2959599) currently fails with `cannot deserialize module: UnknownOpcode(192)`. 
Version `2023-01-01` is known to work.

Downgrade rust nightly version

---

dockerfiles/ci-linux/Dockerfile

This reverts commit d635ef2f071446216371bc36db43b0112bc8397d.
The trappist team has indicated they no longer need us to provide an old nightly; they're simply installing one locally in their cmd-bot script: https://github.com/paritytech/command-bot-scripts/blob/1e8a2e9500af9884181c45fa85a09da0e2f3a53f/commands/bench/lib/bench-all-trappist.sh#L5

Revert "Downgrade rust nightly version (#570)"

---

dockerfiles/ci-unified/Dockerfile

Since v0.1.3 `cargo install mdbook-last-changed` without --locked throws E0308: mismatched types (toml::value::Value)

Use --locked for mdbook-last-changed install

---

.gitlab-ci.yml

`script_failure` covers transient errors, which is included in `always`.

Always auto-retry `ci-unified` builds

---

dockerfiles/ci-unified/Dockerfile

1. remove `binaryen` tools incl. `wasm-opt`, since `cargo-contract` uses the embedded lib now. **Assumes no other projects are using it**
2. remove second installation of `cargo-contract` from `crates.io` installed using nightly toolchain? Perhaps a legacy thing, but `cargo-contract` is already installed earlier [here](https://github.com/paritytech/scripts/blob/d96a16e2f92ee76fe4b9241475ea3e2c1da648a0/dockerfiles/ci-unified/Dockerfile#L147), and we no longer build with `nightly`.

Remove some legacy `contracts` related stuff

---

dockerfiles/ws-health-exporter/README.md
dockerfiles/ws-health-exporter/exporter.py

* if you check container logs you can't understand which check failed. new info logs help with it
* rate of new blocks feature was added. it is disabled by default. it can be useful in some cases

More logs, block rate for ws-health-exporter

---

dockerfiles/terraform/Dockerfile

[This ](https://github.com/paritytech/scripts/commit/a0e304ff984cf6427b0bb4aa929662cbd3b5b782) Broke terraform and vault being accessible from PATH, I'm not sure what the previous change was trying to fix.

Revert spaces fix

---

.gitlab-ci.yml
dockerfiles/ci-unified/Dockerfile
dockerfiles/ci-unified/README.md

* Add `restic` and `bzcat`
* Tweak comments and README
* Explicitly reflect that we use Rust 1.73.0 now

Add `restic` and bump `ci-unified`

---

dockerfiles/substrate-session-keys-grabber/grabber.py

New session key also contains beefy key

[substrate-session-keys-grabber] Add beefy support

---

dockerfiles/ci-unified/Dockerfile

As per discussion [here](https://github.com/paritytech/polkadot-sdk/pull/2518#discussion_r1409418613).

Add `taplo-cli` & `zepter` to `ci-unified`

---

dockerfiles/ci-unified/Dockerfile

Update the unified-ci script with the latest version of the risc-v toolchain and openssl to version 3.1.4

Update rve toolchain in unified image

---

dockerfiles/ci-unified/Dockerfile

Needed for https://github.com/paritytech/ink/pull/2075.

Install `subkey` for `contracts-ci`

---

dockerfiles/ws-health-exporter/exporter.py

Some autodiscovery services of monitoring systems can conflict with the `url` label name. It was replaced by a more specific name.

label's name was changed for ws-health-exporter

---

dockerfiles/terraform/Dockerfile

required for comparison of users in TF state and other APIs

Add python3 in TF image

---

dockerfiles/ci-unified/Dockerfile

Build fails see https://gitlab.parity.io/parity/mirrors/scripts/-/jobs/5311307#L3923

Add `--locked` to `mdbook-graphviz` to fix build

---

dockerfiles/ws-health-exporter/README.md
dockerfiles/ws-health-exporter/exporter.py

Issue: https://github.com/paritytech/helm-charts/issues/330
When `ws-health-exporter` is used as a sidecar in Kubernetes, it adds a delay to the start and stop of the pod.
During startup, the node needs a couple of seconds to reach 10 peers. If we have 2 peers, it should be enough.
During shutdown, the container ignores the signal from Kubernetes, causing it to hang for another 30 seconds while the main container is dead.

optimize ws-health-exporter

---

dockerfiles/ci-unified/Dockerfile
dockerfiles/ci-unified/download-forklift.sh

add forklift binary (and download script just in case) to the ci-unified image

forklift for ci-unified

---

dockerfiles/ci-unified/Dockerfile

This allows Cargo.toml manipulation in CI, primarily, versioning.
Will be useful for publishing crates, based on tags.

Adding `cargo-edit` and `gh` to ci-unified
